# ==============================================================
#   Configuración básica del servidor
# ==============================================================
server.port=3000
spring.application.name=istore

# ==============================================================
#   Base de datos JPA - Conexión a la bd
# ==============================================================
spring.jpa.database=POSTGRESQL
# ====== Conexión la BD alojada en la VM ======
spring.datasource.url=jdbc:postgresql://34.41.45.107:5432/db-istore?currentSchema=public&useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Lima
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
#   Configuración de JPA/Hibernate
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
