# ==============================================================
#   Configuración básica del servidor
# ==============================================================
server.port=3000
spring.application.name=istore

# ==============================================================
#   Base de datos JPA - Conexión a la bd
# ==============================================================
spring.jpa.database=POSTGRESQL
# ====== Conexión la BD alojada en la VM ======
spring.datasource.url=jdbc:postgresql://34.176.50.106:5432/db-istore?currentSchema=public&useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Lima
# spring.datasource.url=jdbc:postgresql://localhost:5432/db-istore
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
#   Configuración de JPA/Hibernate
# ==============================================================
spring.jpa.hibernate.ddl-auto=update

# CONFIGURACIÓN CLOUDINARY
cloudinary.cloud_name=dsekbisuv
cloudinary.api_key=219799538755283
cloudinary.api_secret=T9GhS1qMZ7V06bHPKbQRazzGlx4